# Fine-Tuning Transformers for Arabic Sarcasm Detection

This notebook fine-tunes pre-trained Arabic language models (e.g., `aubmindlab/bert-base-arabertv02`, `asafaya/bert-base-arabic`, or `MARBERT`) on the ArSarcasm-v2 dataset.

In [6]:
import os
import sys

REPO = "Arabic-sarcasm"

if not os.path.exists(f"/content/{REPO}"):
    !git clone https://github.com/cad0m/{REPO}.git /content/{REPO}
else:
    !git -C /content/{REPO} pull

%cd /content/{REPO}

if f"/content/{REPO}" not in sys.path:
    sys.path.insert(0, f"/content/{REPO}")

!pip install -q uv
!uv pip install --system emoji tashaphyne

Already up to date.
/content/Arabic-sarcasm
Using Python 3.13.15 environment at: /usr
Checked 2 packages in 171ms

In [7]:
import shutil
import sys
sys.path.append("..")

import torch
import torch.nn.functional as F
from datasets import Dataset
from scipy.special import softmax
from torch import nn
from transformers import (AutoModel, AutoTokenizer, EarlyStoppingCallback,
                          Trainer, TrainingArguments)

from src.data import get_data
from src.evaluate import log_result, metrics, save_predictions, show
from src.preprocess import build_pipeline
from src.train import best_threshold, count_params, set_seed

MODELS = {
    "arabert": "aubmindlab/bert-base-arabertv02-twitter",
    "marbert": "UBC-NLP/MARBERTv2",
}
PREP = "html+urls+mentions"

In [10]:
for name in MODELS.values():
    AutoModel.from_pretrained(name)

tokenizers = {key: AutoTokenizer.from_pretrained(name) for key, name in MODELS.items()}

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: UBC-NLP/MARBERTv2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [11]:
train, val, test, report = get_data()

prep = build_pipeline(["html", "urls", "mentions"])
for frame in (train, val, test):
    frame["text"] = frame["tweet"].apply(prep)
    frame["sent"] = frame["sentiment"].str.upper().map({"NEG": 0, "NEU": 1, "POS": 2})

counts = train["sarcasm"].value_counts().sort_index()
WEIGHTS = torch.tensor(len(train) / (2 * counts.values), dtype=torch.float)
WEIGHTS

tensor([0.6040, 2.9044])

In [12]:
def to_dataset(frame, tokenizer):
    data = Dataset.from_dict({"text": frame["text"].tolist(),
                              "labels": frame["sarcasm"].tolist(),
                              "sentiment": frame["sent"].tolist()})
    return data.map(lambda b: tokenizer(b["text"], truncation=True, max_length=96,
                                        return_token_type_ids=False),
                    batched=True, remove_columns=["text"])


ds = {key: {"train": to_dataset(train, tok), "val": to_dataset(val, tok), "test": to_dataset(test, tok)}
      for key, tok in tokenizers.items()}

Map:   0%|          | 0/10781 [00:00<?, ? examples/s]

Map:   0%|          | 0/1255 [00:00<?, ? examples/s]

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

Map:   0%|          | 0/10781 [00:00<?, ? examples/s]

Map:   0%|          | 0/1255 [00:00<?, ? examples/s]

Map:   0%|          | 0/3000 [00:00<?, ? examples/s]

In [13]:
class MultiTask(nn.Module):
    def __init__(self, name, weights, lam):
        super().__init__()
        self.encoder = AutoModel.from_pretrained(name)
        for param in self.encoder.parameters():
            param.data = param.data.contiguous()
        size = self.encoder.config.hidden_size
        self.sarcasm_head = nn.Linear(size, 2)
        self.sentiment_head = nn.Linear(size, 3)
        self.register_buffer("weights", weights)
        self.lam = lam

    def forward(self, input_ids, attention_mask, labels=None, sentiment=None):
        cls = self.encoder(input_ids=input_ids, attention_mask=attention_mask).last_hidden_state[:, 0]
        logits = self.sarcasm_head(cls)
        if labels is None:
            return {"logits": logits}
        loss = F.cross_entropy(logits, labels, weight=self.weights)
        loss = loss + self.lam * F.cross_entropy(self.sentiment_head(cls), sentiment)
        return {"loss": loss, "logits": logits}

In [14]:
ARGS = dict(
    num_train_epochs=5, learning_rate=2e-5, weight_decay=0.01, warmup_steps=0.1,
    per_device_train_batch_size=32, per_device_eval_batch_size=64,
    fp16=torch.cuda.is_available(),
    eval_strategy="epoch", save_strategy="epoch", save_total_limit=1,
    load_best_model_at_end=True, metric_for_best_model="f1",
    logging_strategy="epoch", report_to="none",
)


def val_scores(pred):
    proba = softmax(pred.predictions, axis=1)[:, 1]
    return metrics(pred.label_ids, proba, best_threshold(pred.label_ids, proba))


def make_trainer(key, lam, seed):
    set_seed(seed)
    model = MultiTask(MODELS[key], WEIGHTS, lam)
    args = TrainingArguments(output_dir=f"checkpoints/{key}_lam{lam}_seed{seed}", seed=seed, **ARGS)
    return Trainer(model=model, args=args,
                   train_dataset=ds[key]["train"], eval_dataset=ds[key]["val"],
                   processing_class=tokenizers[key], compute_metrics=val_scores,
                   callbacks=[EarlyStoppingCallback(early_stopping_patience=2)])

In [15]:
from pathlib import Path


def predict(trainer, dataset):
    out = trainer.predict(dataset)
    return softmax(out.predictions, axis=1)[:, 1], out.label_ids


def log_run(trainer, result, name, lam, seed, key, final=False):
    seconds = result.metrics["train_runtime"]
    proba, y = predict(trainer, ds[key]["val"])
    threshold = best_threshold(y, proba)
    scores = metrics(y, proba, threshold)
    row = {f"val_{k}": v for k, v in scores.items()}

    if final:
        test_proba, test_y = predict(trainer, ds[key]["test"])
        row |= {f"test_{k}": v for k, v in metrics(test_y, test_proba, threshold).items()}
        save_predictions(name, seed, test["id"], test_y, test_proba, threshold)
        if seed == 42:
            Path("../models").mkdir(exist_ok=True)
            torch.save(trainer.model.state_dict(), f"../models/{name}_seed{seed}.pt")

    log_result(model=name, preprocessing=PREP, seed=seed, lam=lam, threshold=threshold,
               train_time=seconds, trained_params=count_params(trainer.model), **row)
    show(name, scores, threshold, seconds)
    shutil.rmtree(trainer.args.output_dir)

In [28]:
trainer = make_trainer("arabert", lam=0, seed=42)
result = trainer.train()
log_run(trainer, result, "arabert_e1", lam=0, seed=42, key="arabert")

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e1                   f1=0.6726  pr_auc=0.6684  threshold=0.70  562s

In [29]:
trainer = make_trainer("arabert", lam=0.3, seed=42)
result = trainer.train()
log_run(trainer, result, "arabert_e2_lam0.3", lam=0.3, seed=42, key="arabert")

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e2_lam0.3            f1=0.6768  pr_auc=0.6679  threshold=0.66  431s

In [30]:
trainer = make_trainer("arabert", lam=0.5, seed=42)
result = trainer.train()
log_run(trainer, result, "arabert_e2_lam0.5", lam=0.5, seed=42, key="arabert")

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e2_lam0.5            f1=0.6771  pr_auc=0.6690  threshold=0.69  419s

In [31]:
trainer = make_trainer("arabert", lam=1, seed=42)
result = trainer.train()
log_run(trainer, result, "arabert_e2_lam1", lam=1, seed=42, key="arabert")

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e2_lam1              f1=0.6818  pr_auc=0.6803  threshold=0.76  547s

In [32]:
trainer = make_trainer("marbert", lam=0, seed=42)
result = trainer.train()
log_run(trainer, result, "marbert_e1", lam=0, seed=42, key="marbert")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: UBC-NLP/MARBERTv2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

marbert_e1                   f1=0.6531  pr_auc=0.6738  threshold=0.85  370s

In [33]:
trainer = make_trainer("marbert", lam=0.3, seed=42)
result = trainer.train()
log_run(trainer, result, "marbert_e2_lam0.3", lam=0.3, seed=42, key="marbert")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: UBC-NLP/MARBERTv2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

marbert_e2_lam0.3            f1=0.6562  pr_auc=0.6707  threshold=0.70  486s

In [34]:
trainer = make_trainer("marbert", lam=0.5, seed=42)
result = trainer.train()
log_run(trainer, result, "marbert_e2_lam0.5", lam=0.5, seed=42, key="marbert")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: UBC-NLP/MARBERTv2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

marbert_e2_lam0.5            f1=0.6639  pr_auc=0.6746  threshold=0.60  515s

In [35]:
trainer = make_trainer("marbert", lam=1, seed=42)
result = trainer.train()
log_run(trainer, result, "marbert_e2_lam1", lam=1, seed=42, key="marbert")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: UBC-NLP/MARBERTv2
Key                                        | Status     |  |
-------------------------------------------+------------+--+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  |
cls.seq_relationship.weight                | UNEXPECTED |  |
cls.predictions.transform.dense.bias       | UNEXPECTED |  |
cls.seq_relationship.bias                  | UNEXPECTED |  |
cls.predictions.decoder.weight             | UNEXPECTED |  |
cls.predictions.decoder.bias               | UNEXPECTED |  |
cls.predictions.transform.dense.weight     | UNEXPECTED |  |
cls.predictions.bias                       | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

marbert_e2_lam1              f1=0.6667  pr_auc=0.6722  threshold=0.64  639s

In [9]:
import pandas as pd
res = pd.read_csv("/content/Arabic-sarcasm/results/results.csv")
res[["model", "val_f1", "val_pr_auc"]].sort_values("val_f1", ascending=False)

                         model    val_f1  val_pr_auc
104  arabert_frozen_bilstm_att  0.688742    0.691897
109            arabert_e2_lam1  0.681818    0.680326
108          arabert_e2_lam0.5  0.677130    0.668952
107          arabert_e2_lam0.3  0.676790    0.667937
114                 arabert_e1  0.672566    0.668429
..                         ...       ...         ...
27             zeroshot_nli_fr  0.353333    0.274104
39             zeroshot_nli_en  0.352814    0.275327
26             zeroshot_nli_fr  0.351005    0.284253
40             zeroshot_nli_en  0.348964    0.264537
28             zeroshot_nli_fr  0.344482    0.261632

[115 rows x 3 columns]

In [16]:
trainer = make_trainer("arabert", lam=0, seed=42)
result = trainer.train()
log_run(trainer, result, "arabert_e1", lam=0, seed=42, key="arabert", final=True)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e1                   f1=0.6726  pr_auc=0.6684  threshold=0.70  377s

In [17]:
trainer = make_trainer("arabert", lam=0, seed=43)
result = trainer.train()
log_run(trainer, result, "arabert_e1", lam=0, seed=43, key="arabert", final=True)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e1                   f1=0.6636  pr_auc=0.6785  threshold=0.75  336s

In [18]:
trainer = make_trainer("arabert", lam=0, seed=44)
result = trainer.train()
log_run(trainer, result, "arabert_e1", lam=0, seed=44, key="arabert", final=True)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e1                   f1=0.6667  pr_auc=0.6869  threshold=0.48  312s

In [19]:
trainer = make_trainer("arabert", lam=1, seed=42)
result = trainer.train()
log_run(trainer, result, "arabert_e2", lam=1, seed=42, key="arabert", final=True)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e2                   f1=0.6818  pr_auc=0.6803  threshold=0.76  416s

In [20]:
trainer = make_trainer("arabert", lam=1, seed=43)
result = trainer.train()
log_run(trainer, result, "arabert_e2", lam=1, seed=43, key="arabert", final=True)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e2                   f1=0.6906  pr_auc=0.7060  threshold=0.74  456s

In [21]:
trainer = make_trainer("arabert", lam=1, seed=44)
result = trainer.train()
log_run(trainer, result, "arabert_e2", lam=1, seed=44, key="arabert", final=True)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

[transformers] BertModel LOAD REPORT from: aubmindlab/bert-base-arabertv02-twitter
Key                                        | Status     |
-------------------------------------------+------------+-
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
pooler.dense.weight                        | MISSING    |
pooler.dense.bias                          | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

arabert_e2                   f1=0.6737  pr_auc=0.7091  threshold=0.63  313s

In [23]:
res = pd.read_csv("/content/Arabic-sarcasm/results/results.csv")
final = res[res["model"].isin(["arabert_e1", "arabert_e2"]) & res["test_f1"].notna()]

print(final.groupby("model")["seed"].apply(list))
final.groupby("model")[["val_f1", "test_f1", "test_pr_auc", "test_macro_f1"]].agg(["mean", "std"]).round(4)

model
arabert_e1    [42, 43, 44]
arabert_e2    [42, 43, 44]
Name: seed, dtype: object

            val_f1         test_f1         test_pr_auc         test_macro_f1  \
              mean     std    mean     std        mean     std          mean
model
arabert_e1  0.6676  0.0045  0.6029  0.0129      0.6397  0.0178        0.7221
arabert_e2  0.6820  0.0084  0.6028  0.0027      0.6386  0.0079        0.7267


               std
model
arabert_e1  0.0017
arabert_e2  0.0025

In [26]:
print(sorted(os.listdir("/content/Arabic-sarcasm/predictions")))
print(sorted(os.listdir("/content/models")))

['arabert_e1_seed42.csv', 'arabert_e1_seed43.csv', 'arabert_e1_seed44.csv', 'arabert_e2_seed42.csv', 'arabert_e2_seed43.csv', 'arabert_e2_seed44.csv']
['arabert_e1_seed42.pt', 'arabert_e2_seed42.pt']

In [28]:
from google.colab import drive, files
from src.evaluate import ROOT

drive.mount("/content/drive")
!mkdir -p /content/drive/MyDrive/sarcasm_models
!cp ../models/*.pt /content/drive/MyDrive/sarcasm_models/
!cd {ROOT} && zip -r /content/small_outputs.zip results predictions
files.download("/content/small_outputs.zip")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
  adding: results/ (stored 0%)
  adding: results/results.csv (deflated 66%)
  adding: predictions/ (stored 0%)
  adding: predictions/arabert_e1_seed43.csv (deflated 62%)
  adding: predictions/arabert_e1_seed42.csv (deflated 63%)
  adding: predictions/arabert_e2_seed43.csv (deflated 63%)
  adding: predictions/arabert_e2_seed44.csv (deflated 62%)
  adding: predictions/arabert_e1_seed44.csv (deflated 63%)
  adding: predictions/arabert_e2_seed42.csv (deflated 63%)